/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

public class App {
    public static void main(String[] args) {
        // 강사님 코드

        // 변수명 소문자
        String appTitle = "[팀 프로젝트 관리 시스템]";
        String line = "----------------------------------------";
        String menu1 = "1. 회원";
        String menu2 = "2. 팀";
        String menu3 = "3. 프로젝트";
        String menu4 = "4. 게시판";
        String menu5 = "5. 도움말";
        String menu6 = "6. 종료";

        System.out.println(line);
        System.out.println(appTitle);
        System.out.println(menu1);
        System.out.println(menu2);
        System.out.println(menu3);
        System.out.println(menu4);
        System.out.println(menu5);
        System.out.println(menu6);
        System.out.println(line);

        //
        System.out.println("-------------------------------------------일반 변수로 출력해보기");

        String str1 = "1. 회원";
        String str2 = "2. 팀";
        String str3 = "3. 프로젝트";
        String str4 = "4. 게시판";
        String str5 = "5. 도움말";
        String str6 = "6. 종료";

        System.out.println("[팀 프로젝트 관리 시스템]");
        System.out.println(str1);
        System.out.println(str2);
        System.out.println(str3);
        System.out.println(str4);
        System.out.println(str5);
        System.out.println(str6);
        System.out.println("-------------------------------------------일반 변수로 출력해보기");

        System.out.println("-------------------------------------------for문으로 돌려보기");

        String[] str = {
                "1. 회원",
                "2. 팀",
                "3. 프로젝트",
                "4. 게시판",
                "5. 도움말",
                "6. 종료",
        };

        System.out.println("[팀 프로젝트 관리 시스템]");
        for(String item: str) {
            System.out.println(item);
        }

        System.out.println("-------------------------------------------for문으로 돌려보기");
    }
}
