/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

public class App {
    public static void main(String[] args) {
        System.out.println("[팀 프로젝트 관리 시스템]");
    }
}
