/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

import java.util.InputMismatchException;
import java.util.Scanner;

public class App {

//    java.io.InputStream keyboard = System.in;
    // import
    static Scanner keyboardScanner = new Scanner(System.in);
    
    // 배열 저장
    static String[] menus = new String[] {
            "회원",
            "팀",
            "프로젝트",
            "게시판",
            "도움말",
            "종료"
    };
    
    public static void main(String[] args) {
        
        printMenu(); // 메서드에 묶인 코드를 메서드를 실행하는 것을 "메서드를 호출(call)한다"라고 부른다.

        String command;

        while(true) {
            try {
                command = prompt();

                if (command.equals("menu")) {
                    printMenu();
                } else {
                    int menuNo = Integer.parseInt(command); // 문자열을 int 값으로 바꿈.
                    String menuTitle = getMenuTitle(menuNo); // 설명하는 변수

                    /*if (menuTitle != null) {
                        if (menuTitle.equals("종료")) {
                            // 종료 메뉴일 때 반복문을 나간다.
                            break;
                        }
                        System.out.println(menuTitle);
                    } else {
                        System.out.println("유효한 메뉴 번호가 아닙니다.");
                    }*/

                    if (menuTitle == null) {
                        System.out.println("유효한 메뉴 번호가 아닙니다.");
                    } else if (menuTitle.equals("종료")) {
                        break;
                    } else {
                        System.out.println(menuTitle);
                    }
                }

            } catch (NumberFormatException e) {
                System.out.println("숫자로 메뉴 번호를 입력하세요.");
            }
        }

        // 종료하면 어차피 반복문을 나오니까.
        System.out.println("종료합니다.");

        keyboardScanner.close();
    }

    static void printMenu() {
        String boldAnsi = "\033[1m";
        String redAnsi = "\033[31m";
        String resetAnsi = "\033[0m";
        String appTitle = "[팀 프로젝트 관리 시스템]";
        String line = "----------------------------------------";
        
        System.out.println(boldAnsi + line + resetAnsi);
        System.out.println(boldAnsi + appTitle + resetAnsi);

        for (int i = 0; i < menus.length; i++) {
            if (menus[i].equals("종료")) {
                System.out.printf("%s%d. %s%s\n", (boldAnsi + redAnsi), (i + 1), menus[i], resetAnsi);
            } else {
                System.out.printf("%d. %s\n", (i + 1), menus[i]);
            }
        }

        System.out.println(boldAnsi + line + resetAnsi);
    }

    static String prompt() {
        System.out.print("> ");
        return keyboardScanner.nextLine();
    }

    static boolean isValidateMenu(int menuNo) {
        return menuNo >= 1 && menuNo <= menus.length;
    }

    static String getMenuTitle(int menuNo) {
        /*if (isValidateMenu(menuNo)) {
            return menus[menuNo -1];
        }
        return null;*/

        return isValidateMenu(menuNo) ? menus[menuNo -1] : null;
    }
}
