/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

// 04. 키보드 입력 다루기

import java.util.InputMismatchException;

public class App {
    public static void main(String[] args) {
        // 키보드 입력 함수 생성하기
        java.util.Scanner keboardScanner = new java.util.Scanner(System.in);

        String boldAnsi = "\033[1m";
        String redAnsi = "\033[31m";
        String resetAnsi = "\033[0m";
        String line = "---------------------------------------";
        String title = "[팀 프로젝트 관리 시스템]";
        String menu1 = "1. 회원";
        String menu2 = "2. 팀";
        String menu3 = "3. 프로젝트";
        String menu4 = "4. 게시판";
        String menu5 = "5. 도움말";
        String menu6 = "6. 종료";
        
        System.out.println(boldAnsi + line + resetAnsi);
        System.out.println(boldAnsi + title + resetAnsi);
        System.out.println(menu1);
        System.out.println(menu2);
        System.out.println(menu3);
        System.out.println(menu4);
        System.out.println(menu5);
        System.out.println(boldAnsi + redAnsi + menu6 + resetAnsi);
        System.out.println(boldAnsi + line + resetAnsi);

        int menuNo;

        /*System.out.print("> ");
        // scanner 도구를 사용하여 키보드로부터 한 줄의 문자열을 가져올 때 사용하는 명령어
        menuNo = keboardScanner.nextInt();
        System.out.println(menuNo);*/

        // do-while문으로 작성해보기.
        /*do {
            System.out.print("> ");
            menuNo = keboardScanner.nextInt();

            switch(menuNo) {
                case 1:
                    System.out.println("회원");
                    break;
                case 2:
                    System.out.println("팀");
                    break;
                case 3:
                    System.out.println("프로젝트");
                    break;
                case 4:
                    System.out.println("게시판");
                    break;
                case 5:
                    System.out.println("도움말");
                    break;
                case 6:
                    System.out.println("종료합니다.");
                    break;
                default:
                    System.out.println("메뉴 번호가 옳지 않습니다.");
                    break;
            }

            // System.out.println(menuNo);
        } while(menuNo != 6);*/

        // int값이 아닌 다른 값으로 입력 했을 때
        /*boolean validInput = false;
        while(!validInput) {
            System.out.print("> ");

            try {
                // try문 안에 있어야 한다..
                menuNo = keboardScanner.nextInt();

                switch(menuNo) {
                    case 1:
                        System.out.println("회원");
                        break;
                    case 2:
                        System.out.println("팀");
                        break;
                    case 3:
                        System.out.println("프로젝트");
                        break;
                    case 4:
                        System.out.println("게시판");
                        break;
                    case 5:
                        System.out.println("도움말");
                        break;
                    case 6:
                        System.out.println("종료합니다.");
                        validInput = true;
                        break;
                    default:
                        System.out.println("메뉴 번호가 옳지 않습니다.");
                        break;
                }
            } catch(InputMismatchException e) {
                System.out.println("잘못된 입력입니다. 정수를 입력하세요."); // 예외가 발생하면 메시지 출력
                keboardScanner.next();
            }*/

            // 다시 do-while로 작성해볼까..?
            boolean validInput = false;
            do {
                try {
                    System.out.print("> ");
                    menuNo = keboardScanner.nextInt();

                    switch(menuNo) {
                        case 1:
                            System.out.println("회원");
                            break;
                        case 2:
                            System.out.println("팀");
                            break;
                        case 3:
                            System.out.println("프로젝트");
                            break;
                        case 4:
                            System.out.println("게시판");
                            break;
                        case 5:
                            System.out.println("도움말");
                            break;
                        case 6:
                            System.out.println("종료합니다.");
                            validInput = true;
                            break;
                        default:
                            System.out.println("메뉴 번호가 옳지 않습니다.");
                            break;
                    }
                } catch(InputMismatchException e) {
                    System.out.println("잘못된 입력입니다. 정수를 입력하세요."); // 예외가 발생하면 메시지 출력
                    keboardScanner.next();
                }

            } while (!validInput);

        keboardScanner.close();
    }
}
