/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

// 07. 문자열 비교와 데이터 변환 다루기

public class App07 {
    public static void main(String[] args) {
        // 키보드 입력 함수 생성하기
        java.util.Scanner keyboardScanner = new java.util.Scanner(System.in);

        String boldAnsi = "\033[1m";
        String redAnsi = "\033[31m";
        String resetAnsi = "\033[0m";
        String line = "---------------------------------------";
        String title = "[팀 프로젝트 관리 시스템]";
        
        String[] menus = {
                "회원",
                "팀",
                "프로젝트",
                "게시판",
                "도움말",
                "종료"
        };
        
        System.out.println(boldAnsi + line + resetAnsi);
        System.out.println(boldAnsi + title + resetAnsi);

        for (int i = 0; i < menus.length; i++) {
            if (menus[i].equals("종료")) {
                System.out.printf("%s%d. %s%s\n", (boldAnsi + redAnsi), (i + 1), menus[i], resetAnsi);
            } else {
                System.out.printf("%d. %s\n", (i + 1), menus[i]);
            }
        }

        System.out.println(boldAnsi + line + resetAnsi);

        String command;

        while (true) {
            try {
                System.out.print("> ");
                command = keyboardScanner.nextLine(); // nextInt() 대신 nextLine 사용.

                if(command.equals("menu")) {
                    System.out.println(boldAnsi + line + resetAnsi);
                    System.out.println(boldAnsi + title + resetAnsi);

                    for (int i = 0; i < menus.length; i++) {
                        if (menus[i].equals("종료")) {
                            System.out.printf("%s%d. %s%s\n", (boldAnsi + redAnsi), (i + 1), menus[i], resetAnsi);
                        } else {
                            System.out.printf("%d. %s\n", (i + 1), menus[i]);
                        }
                    }

                    System.out.println(boldAnsi + line + resetAnsi);
                } else {
                    int menuNo = Integer.parseInt(command); // command를 여기서 변환..

                    if (menuNo >= 1 && menuNo <= menus.length) {
                        if (menus[menuNo - 1].equals("종료")) {
                            break;
                        } else {
                            System.out.println(menus[menuNo - 1]);
                        }
                    } else {
                        System.out.println("메뉴 번호가 옳지 않습니다.");
                    }
                }

            } catch (NumberFormatException e) {
                System.out.println("메뉴 번호가 아닙니다.");
            }

        }

        System.out.println("종료합니다.");
        keyboardScanner.close();
    }
}
