/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

// 02. 리터럴과 변수를 사용해서 문자열 출력하기.

public class App02 {
    public static void main(String[] args) {
        String line = "---------------------------------------";
        String title = "[팀 프로젝트 관리 시스템]";
        String menu1 = "1. 회원";
        String menu2 = "2. 팀";
        String menu3 = "3. 프로젝트";
        String menu4 = "4. 게시판";
        String menu5 = "5. 도움말";
        String menu6 = "6. 종료";
        
        System.out.println(line);
        System.out.println(title);
        System.out.println(menu1);
        System.out.println(menu2);
        System.out.println(menu3);
        System.out.println(menu4);
        System.out.println(menu5);
        System.out.println(menu6);
        System.out.println(line);
    }
}
