/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.myapp;

// 01. 자바 프로젝트 준비하기
// IntelliJ 파일 열기에서 해당 폴더 안의 settings.gradle로 프로젝트 열기.

public class App01 {
    public static void main(String[] args) {
        System.out.println("[팀 프로젝트 관리 시스템]");
    }
}
